//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArtikal
    {
        public int ArtikalID { get; set; }
        public string ArtikalNaziv { get; set; }
        public string Opis { get; set; }
        public string Kategorija { get; set; }
        public string Proizvodjac { get; set; }
        public string Dobavljac { get; set; }
        public decimal Cena { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
